require('vis')

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
    vis:command('set number')
    vis:command('set cursorline')
    vis:command('set showmatch')
    vis:command('set tabwidth 2')
    vis:command('set expandtab')
    vis:command('set autoindent')
    vis:command('set ignorecase')
end)

vis:map(vis.modes.NORMAL, ' w', ':w<Enter>')
vis:map(vis.modes.NORMAL, ' q', ':q<Enter>')
vis:map(vis.modes.NORMAL, ' wq', ':wq<Enter>')
vis:map(vis.modes.NORMAL, ' e', '$')
vis:map(vis.modes.NORMAL, '-', '$')
vis:map(vis.modes.NORMAL, ' h', '<Escape>')
vis:map(vis.modes.NORMAL, ' n', ':bnext<Enter>')
vis:map(vis.modes.NORMAL, ' p', ':bprev<Enter>')
vis:map(vis.modes.NORMAL, ' ;', ':')
vis:map(vis.modes.NORMAL, ' d', ':split<Enter>')
vis:map(vis.modes.NORMAL, ' dv', ':vsplit<Enter>')
vis:map(vis.modes.INSERT, 'jj', '<Escape>')
